// ApplyDeltaP.comp
#version 460
layout(local_size_x = 128) in;

struct Particle { vec4 x; vec4 v; vec4 p; vec4 color; vec4 meta; };

layout(std430, binding = 0) buffer Particles { Particle particles[]; };
layout(std430, binding = 4) buffer DeltaP    { vec4     deltaP[];    };

uniform uint uNumParticles;

void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (i >= uNumParticles) return;
    particles[i].p.xyz += deltaP[i].xyz;
}
