// ResetVelocities.comp
#version 460
layout(local_size_x = 128) in;

struct Particle {
    vec4 x;
    vec4 v;
    vec4 p;
    vec4 color;
    vec4 meta;
};

layout(std430, binding = 0) buffer SSBO_Particles {
    Particle particles[];
};

// Número total de partículas
layout(location = 0) uniform uint uNumParticles;

void main()
{
    uint id = gl_GlobalInvocationID.x;
    if (id < uNumParticles)
        particles[id].v = vec4(0.0);
}
