#version 460
layout(local_size_x = 128) in;

// Añadir uniforme para el número de elementos
uniform uint uNumElements;

layout(std430, binding = 0) buffer Keys {
    uint keys[];
};

layout(std430, binding = 1) buffer BitMask {
    uint bits[];
};

uniform uint uBit;

void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (i >= uNumElements) return; // Verificar límite
    bits[i] = (keys[i] >> uBit) & 1u;
}