#version 450
layout (local_size_x = 128) in;

layout(std430, binding = 0) readonly  buffer Keys {  uint keys[];  };
layout(std430, binding = 1) writeonly buffer Bits {  uint bits[];  };

uniform uint uBit;          // bit a extraer [0‑31]
uniform uint uNumElements;  // nº elementos válidos

void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (i >= uNumElements) return;

    bits[i] = (keys[i] >> uBit) & 1u;   // 0 ó 1 – nada más
}
