#version 460
layout(local_size_x = 128) in;

// Añadir uniforme para el número de elementos
uniform uint uNumElements;

layout(std430, binding = 2) buffer BitMask {
    uint bits[];
};

layout(std430, binding = 6) buffer Counter {
    uint counter[];
};

void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (i >= uNumElements) return; // Verificar límite
    if (bits[i] == 1u) {
        atomicAdd(counter[0], 1u);
    }
}